addSbtPlugin("io.get-coursier"  % "sbt-coursier" % "1.0.0-RC12")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"  % "0.3.4")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt" % "1.6.0-RC1")
addSbtPlugin("io.spray"         % "sbt-revolver" % "0.9.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix" % "0.6.0-M12")
